"""create tool tables

Revision ID: 006
Revises: 005
Create Date: 2026-03-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 tools 表
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('labels', mysql.JSON(), nullable=True),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('upload_type', sa.String(length=50), nullable=False),
    sa.Column('upload_url', sa.String(length=500), nullable=False),
    sa.Column('install_command', mysql.JSON(), nullable=True),
    sa.Column('tool_list', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_office', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('failed_step_status', sa.String(length=50), nullable=True),
    sa.Column('mcp_server_name', sa.String(length=255), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_index(op.f('ix_tools_status'), 'tools', ['status'], unique=False)
    op.create_index(op.f('ix_tools_upload_url'), 'tools', ['upload_url'], unique=False)
    op.create_index(op.f('ix_tools_user_id'), 'tools', ['user_id'], unique=False)

    # 创建 tool_versions 表
    op.create_table('tool_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('config', mysql.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_versions_id'), 'tool_versions', ['id'], unique=False)
    op.create_index(op.f('ix_tool_versions_tool_id'), 'tool_versions', ['tool_id'], unique=False)

    # 创建 user_tools 表
    op.create_table('user_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tools_id'), 'user_tools', ['id'], unique=False)
    op.create_index(op.f('ix_user_tools_tool_id'), 'user_tools', ['tool_id'], unique=False)
    op.create_index(op.f('ix_user_tools_user_id'), 'user_tools', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tools_user_id'), table_name='user_tools')
    op.drop_index(op.f('ix_user_tools_tool_id'), table_name='user_tools')
    op.drop_index(op.f('ix_user_tools_id'), table_name='user_tools')
    op.drop_table('user_tools')
    op.drop_index(op.f('ix_tool_versions_tool_id'), table_name='tool_versions')
    op.drop_index(op.f('ix_tool_versions_id'), table_name='tool_versions')
    op.drop_table('tool_versions')
    op.drop_index(op.f('ix_tools_user_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_upload_url'), table_name='tools')
    op.drop_index(op.f('ix_tools_status'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    # ### end Alembic commands ###