"""create scheduled task tables

Revision ID: 007
Revises: 006
Create Date: 2026-04-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 scheduled_tasks 表
    op.create_table('scheduled_tasks',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('user_id', sa.String(36), nullable=False),
        sa.Column('agent_id', sa.String(36), nullable=False),
        sa.Column('session_id', sa.String(36), nullable=False),
        sa.Column('content', sa.String(10000), nullable=False),
        sa.Column('repeat_type', sa.Enum('immediate', 'interval', 'daily', 'weekly', 'custom', name='repeattype'), nullable=False),
        sa.Column('repeat_config', mysql.JSON(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'paused', name='scheduletaskstatus'), nullable=False),
        sa.Column('last_execute_time', sa.DateTime(), nullable=True),
        sa.Column('next_execute_time', sa.DateTime(), nullable=False),
        sa.Column('max_retry_count', sa.Integer(), nullable=False, server_default='3'),
        sa.Column('timeout_minutes', sa.Integer(), nullable=False, server_default='30'),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('notify_on_failure', sa.Boolean(), nullable=False, server_default='1'),
        sa.Column('docker_image', sa.String(255), nullable=False, server_default='agentx/task-sandbox:latest'),
        sa.Column('resource_quota', mysql.JSON(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_user_id'), 'scheduled_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_agent_id'), 'scheduled_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_session_id'), 'scheduled_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_status'), 'scheduled_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_next_execute_time'), 'scheduled_tasks', ['next_execute_time'], unique=False)

    # 创建 task_execution_logs 表
    op.create_table('task_execution_logs',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('task_id', sa.String(36), nullable=False),
        sa.Column('execute_time', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('result', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('container_id', sa.String(64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_logs_task_id'), 'task_execution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_execution_logs_execute_time'), 'task_execution_logs', ['execute_time'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_execution_logs_execute_time'), table_name='task_execution_logs')
    op.drop_index(op.f('ix_task_execution_logs_task_id'), table_name='task_execution_logs')
    op.drop_table('task_execution_logs')

    op.drop_index(op.f('ix_scheduled_tasks_next_execute_time'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_status'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_session_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_agent_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_user_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
